#!/usr/bin/env node
/**
 * Bump the version across all packages and crates in the monorepo.
 *
 * Usage:
 *   node scripts/bump-version.mjs <version>
 *
 * Examples:
 *   node scripts/bump-version.mjs 0.0.1-beta.3
 *   node scripts/bump-version.mjs 0.1.0
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const version = process.argv[2];
if (!version) {
  console.error('Usage: node scripts/bump-version.mjs <version>');
  console.error('Example: node scripts/bump-version.mjs 0.0.1-beta.3');
  process.exit(1);
}

if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
  console.error(`Invalid version format: "${version}"`);
  console.error('Expected semver like: 0.1.0  or  0.1.0-beta.3');
  process.exit(1);
}

const isPrerelease = version.includes('-');
const npmTag = isPrerelease ? version.split('-')[1].split('.')[0] : 'latest';

console.log(`Bumping all packages to ${version}${isPrerelease ? ` (pre-release, npm tag: ${npmTag})` : ''}\n`);

// ── Helpers ──────────────────────────────────────────────────────────────────

function updateFile(relPath, transform) {
  const abs = resolve(ROOT, relPath);
  const original = readFileSync(abs, 'utf8');
  const updated = transform(original);
  if (updated === original) {
    console.log(`  (unchanged) ${relPath}`);
  } else {
    writeFileSync(abs, updated);
    console.log(`  updated     ${relPath}`);
  }
}

function updateJson(relPath, updater) {
  updateFile(relPath, (content) => {
    const obj = JSON.parse(content);
    updater(obj);
    return JSON.stringify(obj, null, 2) + '\n';
  });
}

// Replace a bare `version = "x.y.z"` line (TOML standalone field, not inline table)
const TOML_VERSION_LINE = /^(version\s*=\s*)"[\d.]+(?:-[\w.]+)?"/m;

// ── npm packages ─────────────────────────────────────────────────────────────

console.log('npm packages:');

updateJson('plugin-agency/package.json', (pkg) => {
  pkg.version = version;
  pkg.dependencies['@muselab/busbar-sf-agentscript'] = version;
});

updateJson('tree-sitter-agentscript/package.json',             (pkg) => { pkg.version = version; });
updateJson('packages/package.json',                            (pkg) => { pkg.version = version; });
updateJson('agent-script-recipes/package.json',                (pkg) => { pkg.version = version; });
updateJson('zed-extension/grammars/agentscript/package.json',  (pkg) => { pkg.version = version; });

// pkg/package.json is generated by wasm-pack but keep the local copy in sync
updateJson('pkg/package.json', (pkg) => { pkg.version = version; });

// ── Rust workspace ────────────────────────────────────────────────────────────

console.log('\nRust crates:');

// Root Cargo.toml: update the [workspace.package] version line AND
// the inline versions for internal workspace deps like:
//   busbar-sf-agentscript = { version = "0.0.1", path = "." }
updateFile('Cargo.toml', (content) => {
  // Standalone version line under [workspace.package]
  let updated = content.replace(TOML_VERSION_LINE, `$1"${version}"`);
  // Inline { version = "x.y.z", path = "..." } for internal path deps
  updated = updated.replace(
    /(\{\s*version\s*=\s*)"[\d.]+(?:-[\w.]+)?(\s*",\s*path\s*=)/g,
    `$1"${version}$2`
  );
  return updated;
});

// zed-extension has its own hardcoded version (does not inherit workspace.version)
updateFile('zed-extension/Cargo.toml',    (c) => c.replace(TOML_VERSION_LINE, `$1"${version}"`));
updateFile('zed-extension/extension.toml', (c) => c.replace(TOML_VERSION_LINE, `$1"${version}"`));

// ── CI workflow ───────────────────────────────────────────────────────────────
// NOTE: ci.yml no longer hardcodes a version — it reads from Cargo.toml at runtime.
// No workflow patching needed here.

// ── Summary ───────────────────────────────────────────────────────────────────

const prelNote = isPrerelease
  ? `\nPre-release notes:\n  - npm packages will publish with --tag ${npmTag}\n  - Rust crates will NOT publish to crates.io (pre-releases are skipped)\n`
  : '';

console.log(`
Done! All packages set to ${version}.
${prelNote}
Next steps:
  1. Review changes:   git diff
  2. Build & test:     cd plugin-agency && npm run build && npm test
  3. Commit:           git commit -am "chore: bump version to ${version}"
  4. Tag & push:       git tag v${version} && git push origin main --tags
`);
